filter:
    excluded_paths: [tests/_support/_generated/*]
checks:
    php:
        code_rating: true
        verify_property_names: false
        use_statement_alias_conflict: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        unused_variables: true
        unused_properties: true
        unused_parameters: false
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        sql_injection_vulnerabilities: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_properties: true
        require_scope_for_methods: true
        require_php_tag_first: true
        psr2_switch_declaration: true
        psr2_class_declaration: true
        property_assignments: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        precedence_mistakes: true
        precedence_in_conditions: true
        php5_style_constructor: true
        parse_doc_comments: true
        parameters_in_camelcaps: false
        parameter_non_unique: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_private_members: true
        overriding_parameter: true
        optional_parameters_at_the_end: true
        one_class_per_file: true
        non_commented_empty_catch_block: true
        no_unnecessary_if: true
        no_unnecessary_final_modifier: true
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        no_trait_type_hints: true
        no_trailing_whitespace: true
        no_short_open_tag: true
        no_property_on_interface: true
        no_non_implemented_abstract_methods: true
        no_goto: true
        no_global_keyword: true
        no_exit: true
        no_eval: true
        no_error_suppression: true
        no_empty_statements: true
        no_duplicate_arguments: true
        no_debug_code: true
        no_commented_out_code: true
        more_specific_types_in_doc_comments: true
        missing_arguments: true
        method_calls_on_non_object: true
        line_length:
            max_length: '120'
        instanceof_class_exists: true
        function_in_camel_caps: true
        foreach_usable_as_reference: true
        foreach_traversable: true
        encourage_single_quotes: true
        encourage_shallow_comparison: true
        encourage_postdec_operator: true
        duplication: true
        deprecated_code_usage: true
        deadlock_detection_in_loops: true
        comparison_always_same_result: true
        code_rating: true
        closure_use_not_conflicting: true
        closure_use_modifiable: true
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        catch_class_exists: true
        call_to_parent_method: true
        blank_line_after_namespace_declaration: true
        avoid_useless_overridden_methods: true
        avoid_usage_of_logical_operators: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_superglobals: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_length_functions_in_loops: true
        avoid_fixme_comments: true
        avoid_duplicate_types: true
        avoid_corrupting_byteorder_marks: true
        avoid_conflicting_incrementers: true
        avoid_closing_tag: true
        assignment_of_null_return: true
        argument_type_checks: true
        align_assignments: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            constants:
                true_false_null: lower
tools:
    external_code_coverage: false
    php_analyzer: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
            sniffs: { generic: { formatting: { multiple_statement_alignment_sniff: false } } }
    php_cpd:
        enabled: false # solicitado por scrutinizer para usar php_analyzer
        excluded_dirs: [vendor, tests]
build:
    environment:
        php:
            version: 7.1
    nodes:
        my-tests:
            environment:
                mysql: 5.6
            project_setup:
                before:
                    # crear la base de datos, el nombre tiene que coincidir con la base
                    # del archivo `environments/dev/common/config/main-local.php`
                    - mysql -e "create database yii2_formgenerator_test"
            tests:
                before:
                    # run migrations
                    - composer deploy-tests
                override:
                    # test coverage
                    -
                        # comando de coverage
                        command: composer run-coverage
                        coverage:
                            file: 'tests/_output/coverage.xml'
                            format: 'clover'
                        idle_timeout: 1800
        analysis:
            project_setup:
                override: [true]
                
            tests:
                override:
                    - php-scrutinizer-run